[package]
name = "striem_api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "striem_api"
path = "src/main.rs"

[dependencies]
striem_common = {"path" = "../common"}
striem_config = {"path" = "../config"}
striem_detection = {"path" = "../detection"}
striem_telemetry = {"path" = "../telemetry"}
arc-swap.workspace = true
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
env_logger.workspace = true
erased-serde.workspace = true
log.workspace = true
reqwest.workspace = true
rmcp = { "workspace" = true, "optional" = true }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tonic.workspace = true
tower-http.workspace = true
uuid.workspace = true

[features]
mcp = ["dep:rmcp"]

[dev-dependencies]
tempfile = "3"
