cargo-features = ["codegen-backend"]

[profile.dev]
codegen-backend = "cranelift"

[workspace]
resolver = "3"
default-members = ["lib/api", "lib/detection"]
members = [ "lib/*" ]

[workspace.package]
name = "StrIEM"
version = "0.1.0"
edition = "2024"
license = "MPLv2"
repository = "https://github.com/striemhq/striem"
readme = "README.md"
keywords = ["sigma", "detection", "security", "secops", "siem"]
category = ["security"]
description = "an open-source SIEM powered by Vector"

[workspace.dependencies]
anyhow = "1.0"
arc-swap = "1"
arrow-json = "58"
axum = { version = "0.8"}
backoff = { version = "0.4", features = ["tokio"]}
chrono = { version = "0.4", features = ["serde"] }
config = "0.15"
duckdb = { version = "1.10504", features = ["modern-full", "json", "parquet", "vtab", "bundled", "r2d2" ] }
env_logger = "0.11"
erased-serde = "0.4"
log = "0.4"
prost = { version = "0.13" }
prost-types = "0.13"
r2d2 = "0.8"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rmcp = { version = "0.8", features = ["client", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"] }
rsigma-eval = { git = "http://github.com/sonnens/rsigma", branch = "logsource_extractor_trait" }
rsigma-parser = { git = "http://github.com/sonnens/rsigma", branch = "logsource_extractor_trait" }
rsigma-runtime = { git = "http://github.com/sonnens/rsigma", branch = "logsource_extractor_trait" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sigmars = { git = "https://github.com/crowdalert/sigmars.git", branch = "compat" }
tokio = { version = "1.41", features = ["full"] }
tokio-stream = "0.1"
toml = { version = "0.9", default-features = false, features = ["serde", "display"] }
tonic = { version = "0.13", default-features = false, features = ["transport", "codegen", "prost", "gzip", "router"] }
tonic-build = { version = "0.13", default-features = false, features = ["transport", "prost"] }
tower-http = { version = "0.6", features = ["fs", "cors"] }
url = "2.5"
uuid = "1.23"
