apiVersion: v1
kind: Service
metadata:
  name: {{ include "striem.api.fullname" . }}
  labels:
    {{- include "striem.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "striem.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
